"""changed models

Revision ID: 4c464e011370
Revises: c22dd8feb99f
Create Date: 2023-05-08 20:24:40.057545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c464e011370'
down_revision = 'c22dd8feb99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    # ### end Alembic commands ###
