"""adds Planet model

Revision ID: 94b66ffc60e6
Revises: 
Create Date: 2023-04-28 14:42:16.449873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b66ffc60e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('planet', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('planet', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
