"""created Moon model

Revision ID: c22dd8feb99f
Revises: e6280fd69a02
Create Date: 2023-05-08 15:17:02.930584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22dd8feb99f'
down_revision = 'e6280fd69a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('planet', 'moons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('moon')
    # ### end Alembic commands ###
