"""added relationship to Planet

Revision ID: ed6e0fca0d96
Revises: 4c464e011370
Create Date: 2023-05-08 20:33:44.207698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6e0fca0d96'
down_revision = '4c464e011370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planet_moon_id_fkey', 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_moon_id_fkey', 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###
