"""Add atribute to planet color

Revision ID: f925f9866148
Revises: 5d0608e7a702
Create Date: 2023-04-27 14:48:28.481212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f925f9866148'
down_revision = '5d0608e7a702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'color')
    # ### end Alembic commands ###
